<?php
/**
 * User: UyenTTT
 * Date: 16/11/2015
 * Time: 3:11 PM
 */

return array(
    'HOME'                      => 'Home',
    'CATEGORIES'                => 'Danh Mục',
    'REPORT'                    => 'Báo Cáo',
    'REPORT_SECTION'            => 'Báo Cáo',
    'RPT_AREA_AFFECT_COMPANY'   => 'Ảnh Hưởng Của Tổ/Quận/Huyện Đến Phòng/Đài/MBF HCM',
    'RPT_SUMMARY_BY_AREA'       => 'Tổng Hợp Theo Tổ/Quận/Huyện',
    'RPT_DETAIL_BY_AREA'        => 'Chi Tiết Theo Tổ/Quận/Huyện',
    'RPT_DETAIL_BY_POSITION'    => 'Chi Tiết Theo Chức Danh',
    'RPT_KPI_RESULT'            => 'Kết Quả KPI',
    'RPT_IMPLEMENT_BY_COMPANY'  => 'Thực Hiện Của Phòng/Đài/MBF HCM',
    'RPT_IMPLEMENT_BY_EMPLOYEE' => 'Thực Hiện Của Cá Nhân',
    'RPT_IMPLEMENT_BY_POSITION' => 'Thực Hiện Của Chức Danh',
    'RPT_IMPLEMENT_BY_MONTH'    => 'Kết Quả KPI Theo Tháng',
    'RPT_PLAN_BY_AREA'          => 'Kế Hoạch Theo Tổ/Quận/Huyện',
    'RPT_IMPLEMENT_BY_AREA'     => 'Thực Hiện Theo Tổ/Quận/Huyện',
    'CATEGORIES_SECTION'        => 'Quản Lý Đơn Vị Và Người Dùng',
    'CORPORATION'               => 'Công ty',
    'COMPANY'                   => 'Phòng/Đài/MBF HCM',
    'AREA'                      => 'Tổ/Quận/Huyện',
    'GROUP'                     => 'Nhóm/Cửa hàng',
    'POSITION'                  => 'Chức Danh',
    'EMPLOYEE'                  => 'Nhân Viên',
    'ACCESS_LEVEL'              => 'Mức Truy Cập',
    'UNIT'                      => 'Đơn Vị Tính',
    'GOAL_SECTION'              => 'Quản Lý Chỉ Tiêu',
    'GOAL_1'                    => 'Mục Tiêu',
    'GOAL_2'                    => 'Chỉ Tiêu',
    'IMPORTANT_LEVEL_SECTION'   => 'Quản Lý Tỷ Trọng',
    'IMPORTANT_LEVEL'           => 'Quản Lý Tỷ Trọng',
    'TARGET_VALUE_SECTION'      => 'Quản Lý Kế Hoạch/Thực Hiện',
    'ADMIN_SECTION'             => 'Quản Trị',
    'IMPORT'                    => 'Import File Excel',
    'VIEW_LOG'                  => 'Xem Log',
    'LOCK_DATA'                 => 'Khóa Dữ Liệu',
    'ADD'                       => 'Thêm Mới',
    'UPDATE'                    => 'Cập Nhật',
    'DELETE'                    => 'Xóa Dữ Liệu',
    'PERMISSION'                => 'Phân Quyền',
    'PERMISSION_USER'           => 'Người Dùng',
    'PERMISSION_FUNCTION'       => 'Chức năng',
    'PERMISSION_VIEW_DETAIL'    => 'Xem Chi Tiết',
    'TITLE_PERMISSION_USER'     => 'Phân Quyền Người Dùng',
    'TITLE_PERMISSION_FUNCTION' => 'Phân Quyền Chức Năng',
    'TITLE_PERMISSION_VIEW_DETAIL' => 'Xem Chi Tiết Phân Quyền',

    'ERR_IMPORT_FILE_INVALID'   => 'Import không đúng file. Vui lòng kiểm tra lại.',
    'ERR_INDEX_SHEET_NULL'      => 'Vui lòng nhập danh sách sheet trước khi import!',
    'ERR_INDEX_SHEET_INVALID'   => 'Danh sách sheet không hợp lệ, vui lòng nhập lại! Ví dụ: 1,2,3,...',
    'ERR_OVER_NUMBER_SHEET'     => 'Danh sách sheet không hợp lệ, Danh sách sheet vượt quá số lượng sheet trong file import!',
    'ERR_IMPORT_UNSUCCESSFUL'   => ' Import không thành công vì tồn tại các dòng bị lỗi dữ liệu:',

    'ERR_LIST_POSITION'         => ' Danh sách chức danh lỗi:',
    'ERR_LIST_EMPLOYEE'         => ' Danh sách nhân viên lỗi:',
    'ERR_LIST_GOAL_CODE'        => ' Mã mục tiêu lỗi dòng: ',
    'ERR_AREA_CODE_APPLY'       => ' Mã Tổ/Quận/Huyện lỗi: ',
    'ERR_POS_CODE_APPLY'        => ' Mã Chức danh lỗi: ',
    'ERR_COMP_CODE_APPLY'       => ' Mã Phòng/Đài/MBF HCM lỗi: ',
    'ERR_LOCK_DATA_ALL_MONTH'   => ' Dữ liệu các tháng đang khóa.',
    'ERR_MONTH_APPLY'           => ' Tháng áp dụng lỗi.',
    'ERR_YEAR_APPLY'            => ' Năm áp dụng lỗi.',
    'ERR_GOAL_CODE'             => 'Mã mục tiêu lỗi dòng: ',

    'WARN_CHECK_DATA'           => ' Vui lòng kiểm tra lại dữ liệu:',
    'WARN_NOT_PRIORITY_POS'     => 'chưa import tỷ trọng tháng',
    'WARN_NOT_TARGET_POS'       => 'chưa import kế hoạch tháng',
    'WARN_NOT_PRIORITY_All_POS' => 'chưa import tỷ trọng cho tất cả chức danh tháng',
    'WARN_OVERRIDE_DATA'        => 'đã tồn tại kế hoạch tháng:',
    'WARN_OVERRIDE_PRI'         => 'đã tồn tại tỷ trọng tháng:',
    'WARN_OVERRIDE_PERFORM'     => 'đã tồn tại thực hiện tháng:',
    'ALERT_SUCCESS_MMS_TP'      => 'đã import thành công kế hoạch tháng',
    'ALERT_SUCCESS_MMS_PP'      => 'đã import thành công thực hiện tháng',

    'NULL_YEAR_APPLY'           => 'Năm áp dụng rỗng.',
    'NULL_MONTH_APPLY'          => 'Tháng áp dụng rỗng.',
    'NULL_TITLE_FILE'           => 'Tiêu đề file import rỗng.',
    'NULL_AREA_APPLY'           => 'Mã Tổ/Quận/Huyện rỗng.',
    'NULL_COMP_APPLY'           => 'Mã Phòng/Đài/MBF HCM rỗng.',
    'NULL_POS_APPLY'            => 'Mã Chức danh rỗng.',
    'NULL_GOAL_CODE'            => 'Mã mục tiêu rỗng dòng: ',
    'NULL_EMPLOYEE_CODE'        => 'Mã nhân viên rỗng tại: ',

    'NULL_AREA_DB'              => 'Vui lòng Thêm mới Tổ/Quận/Huyện ',
    'NULL_COMPANY_DB'           => 'Vui lòng Thêm mới Phòng/Đài/MBF HCM ',
    'NULL_POSITION_DB'          => 'Vui lòng Thêm mới Chức danh ',
    'NULL_EMPLOYEE_DB'          => 'Vui lòng import Nhân viên ',
    'NULL_GOAL_DB'              => 'Vui lòng import Mục tiêu ',

    'SUFF_IMPORT_PE_NULL_DB'    => ' trước khi import Thực hiện cho nhân viên!',
    'SUFF_IMPORT_TA_NULL_DB'    => ' trước khi import Kế hoạch cho Tổ/Quận/Huyện!',

    'KHCD'                      => 'KHCD',
    'THCD'                      => 'THCD',
    'SUPPORT_SECTION'           => 'Hỗ Trợ',
    'CALCULATE_KPI'             => 'Tính KPI',
    'SPT_DOWNLOAD_USERGUIDE'    => 'Tải Hướng Dẫn Sử Dụng',
    'USERGUIDE_PATH'            => '/docs/KPI_HuongDanSuDung.docx',
    'ACCESS_DENIED'             => 'Bạn không có quyền sử dụng chức năng này! <br/>Vui lòng liên hệ Quản trị viên để biết thêm chi tiết.'

);